### ISSUE TITLE
ERROR: Dependency "glesv2" on efl

### ISSUE THREAD

**Issue by frankiejol** [batden/eligible#2]
Hey thank you for these scripts. I used to build E myself but since they use this meson thingie I am no longer able to.

eligible used to work fine but I can no longer update nor install in Bionic. I did a git pull and copied eligible.sh to my downloads directory to make sure it is updated.

When it build efl it fails with missing glesv2
```
Run-time dependency glesv2 found: NO (tried pkgconfig and cmake)

src/lib/evas/meson.build:201:4: ERROR: Dependency "glesv2" not found, tried pkgconfig and cmake
```

The same error from the log:
```
PKG_CONFIG_PATH:
Called `/usr/bin/pkg-config --modversion glesv2` -> 1

CMake binary for MachineChoice.HOST is cached.
Run-time dependency glesv2 found: NO (tried pkgconfig and cmake)

src/lib/evas/meson.build:201:4: ERROR: Dependency "glesv2" not found, tried pkgconfig and cmake
```

I checked glesv2 package, I didn't find it but I installed those just in case, without luck:

- libcogl-gles2-20
- libcogl-gles2-dev
- libgles1
- libgles2
- libgles2-mesa-dev

Maybe am I missing something ? thank you.

**Comment by batden** [comment]
Hi frankiejol,
That's weird. It should work since all the dependencies are installed.
Please post the output of the following commands:
`ldconfig -p | grep libGLESv2`
`locate libGLESv2`

**Comment by frankiejol** [comment]
Hey, thank you for answering so fast @batden .We may have a reason here because there are a bunch of libGLESv2 around

ldconfig -p | grep libGLESv2
```
	libGLESv2.so.2 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libGLESv2.so.2
	libGLESv2.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libGLESv2.so
```

locate libGLESv2
```
/home/frankie/Games/league-of-legends/drive_c/windows/syswow64/gecko/2.47/wine_gecko/libGLESv2.dll
/snap/discord/101/usr/share/discord/libGLESv2.so
/snap/discord/101/usr/share/discord/swiftshader/libGLESv2.so
/snap/discord/93/usr/share/discord/libGLESv2.so
/snap/discord/93/usr/share/discord/swiftshader/libGLESv2.so
/usr/lib/chromium-browser/swiftshader/libGLESv2.so
/usr/lib/x86_64-linux-gnu/libGLESv2.so
/usr/lib/x86_64-linux-gnu/libGLESv2.so.2
/usr/lib/x86_64-linux-gnu/libGLESv2.so.2.0.0
/usr/share/spotify/libGLESv2.so
/usr/share/spotify/swiftshader/libGLESv2.so
```

inxi -G
```
Graphics:  Card: Intel Device 3e92
           Display Server: X.Org 1.20.5
           drivers: modesetting (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.00hz
           OpenGL: renderer: llvmpipe (LLVM 8.0, 256 bits)
           version: 3.3 Mesa 19.1.2 - padoka PPA

```
uname -r
`4.15.0-72-generic`

**Comment by batden** [comment]
> OpenGL: renderer: llvmpipe (LLVM 8.0, 256 bits)

It seems that your system is not using your physical GPU but a software renderer that doesn't support glesv2.
You may need to install a hardware accelerated driver for your graphics card and switch to it.

Then reboot your system and test your settings with:
`glxinfo | egrep "OpenGL vendor | OpenGL renderer"`

**Comment by frankiejol** [comment]
I have been struggling with this intel driver for a while unsuccessfully. I will try harder. So I close the issue because it is not _eligible_ related.
Thank you.

**Comment by batden** [comment]
I reopen it because I'm still investigating the issue. Looks like there is something wrong with the padoka PPA (mesa version mismatch, bad symlink...?). I enabled it on one of my computers and I got the same error: " Dependency "glesv2" not found, tried pkgconfig and cmake"
And this issue seems not related to the llvmpipe renderer...

**Comment by batden** [comment]
Found it!
Switching to the **unstable** padoka PPA did the trick.
Here you go: https://launchpad.net/~paulo-miguel-dias/+archive/ubuntu/mesa/
